name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['8.4']

    name: PHP ${{ matrix.php }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer:v2

      - name: Install dependencies
        run: composer update --no-interaction --no-progress

      - name: PHPStan
        run: make phpstan

      - name: PHPUnit
        run: make test
